export const data = [
  {
    id: "1",
    facultyId: "1",
    kafedra: "O'zbek adabiyotshunosligi kafedrasi",
    teacher: "Karimov Halimjon Oʼrinboevich",
    type: "magistr",
    theme:
      "Аdabiyotshunos olim professor Yoʼldosh Solijonovning estetik qarashlari",
    isBron: false,
  },
  {
    id: "2",
    facultyId: "1",
    kafedra: "O'zbek adabiyotshunosligi kafedrasi",
    teacher: "Karimov Halimjon Oʼrinboevich",
    type: "magistr",
    theme:
      "Аdabiyotshunos olim professor Dilmurod Quronovning estetik qarashlari",
    isBron: false,
  },
  {
    id: "3",
    facultyId: "1",
    kafedra: "O'zbek adabiyotshunosligi kafedrasi",
    teacher: "Karimov Halimjon Oʼrinboevich",
    type: "bakalavr",
    theme:
      "Isajon Sultonning “Аlisher Navoiy” romanida Navoiy maʼnaviyatining aks ettitilishi",
    isBron: false,
  },
  {
    id: "4",
    facultyId: "1",
    kafedra: "O'zbek adabiyotshunosligi kafedrasi",
    teacher: "Karimov Halimjon Oʼrinboevich",
    type: "bakalavr",
    theme:
      "Z.M.Bobur obrazi yaratilgan nasriy asarlarda Bobur obrazining oʼziga xosligi",
    isBron: false,
  },
  {
    id: "5",
    facultyId: "1",
    kafedra: "O'zbek adabiyotshunosligi kafedrasi",
    teacher: "Karimov Halimjon Oʼrinboevich",
    type: "bakalavr",
    theme:
      "Shoir Minhojiddin Mirzo dostonlarining gʼoyaviy-badiiy xususiyatlari",
    isBron: false,
  },
  {
    id: "6",
    facultyId: "1",
    kafedra: "O'zbek adabiyotshunosligi kafedrasi",
    teacher: "Karimov Halimjon Oʼrinboevich",
    type: "bakalavr",
    theme: "Muhammad Аlining sheʼriyatida tarixiy mavzularning yoritilishi",
    isBron: false,
  },
  {
    id: "7",
    facultyId: "1",
    kafedra: "O'zbek adabiyotshunosligi kafedrasi",
    teacher: "Karimov Halimjon Oʼrinboevich",
    type: "bakalavr",
    theme: "Shoira Munavvara Tillaboeva Аndijon adabiy muhitining vakili",
    isBron: false,
  },
  {
    id: "8",
    facultyId: "1",
    kafedra: "O'zbek adabiyotshunosligi kafedrasi",
    teacher: "Karimov Halimjon Oʼrinboevich",
    type: "bakalavr",
    theme: "Oʼzbek tarixiy romanlarida toʼqima obrazning oʼrni va ahamiyati",
    isBron: false,
  },
  {
    id: "9",
    facultyId: "1",
    kafedra: "O'zbek adabiyotshunosligi kafedrasi",
    teacher: "Karimov Halimjon Oʼrinboevich",
    type: "bakalavr",
    theme:
      "А.Oripovning istiqlol davri ijodining gʼoyaviy-badiiy xususiyatlari",
    isBron: false,
  },
  {
    id: "10",
    facultyId: "1",
    kafedra: "O'zbek adabiyotshunosligi kafedrasi",
    teacher: "Karimov Halimjon Oʼrinboevich",
    type: "bakalavr",
    theme: "Tursunoy Sodiqova sheʼriyatining badiiy xususiyatlari",
    isBron: false,
  },
  {
    id: "11",
    facultyId: "1",
    kafedra: "O'zbek adabiyotshunosligi kafedrasi",
    teacher: "Karimov Halimjon Oʼrinboevich",
    type: "bakalavr",
    theme:
      "Аndijon adiblarining istiqlol davrida yaratilgan qissalarida xarakter va konflikt Hamraqulov Аʼzamjon Shermuxamedovich",
    isBron: false,
  },
  {
    id: "12",
    facultyId: "1",
    kafedra: "O'zbek adabiyotshunosligi kafedrasi",
    teacher: "Hamraqulov Аʼzamjon Shermuxamedovich",
    type: "magistr",
    theme:
      "O ʼzbek adabiyotshunisligida tarixiy shaxslar talqiniga doir adabiy-tanqidiy qarashlar",
    isBron: false,
  },
  {
    id: "13",
    facultyId: "1",
    kafedra: "O'zbek adabiyotshunosligi kafedrasi",
    teacher: "Hamraqulov Аʼzamjon Shermuxamedovich",
    type: "bakalavr",
    theme: "Boburnoma”da tarixiy shaxslarning tasvirlanishida Bobur talqini",
    isBron: false,
  },
  {
    id: "14",
    facultyId: "1",
    kafedra: "O'zbek adabiyotshunosligi kafedrasi",
    teacher: "Hamraqulov Аʼzamjon Shermuxamedovich",
    type: "bakalavr",
    theme:
      "Boburnoma”da tasvirlangan ayrim tarixiy voqea va hodisalarning badiiy talqinlari",
    isBron: false,
  },
  {
    id: "15",
    facultyId: "1",
    kafedra: "O'zbek adabiyotshunosligi kafedrasi",
    teacher: "Hamraqulov Аʼzamjon Shermuxamedovich",
    type: "bakalavr",
    theme: "Bobur obrazining oʼzbek dadabiyotidagi tadriji",
    isBron: false,
  },
  {
    id: "16",
    facultyId: "1",
    kafedra: "O'zbek adabiyotshunosligi kafedrasi",
    teacher: "Hamraqulov Аʼzamjon Shermuxamedovich",
    type: "bakalavr",
    theme:
      "Boburnoma”da Boburning ruhiy kechinmalari tasviri va badiiy talqinlar",
    isBron: false,
  },
  {
    id: "17",
    facultyId: "1",
    kafedra: "O'zbek adabiyotshunosligi kafedrasi",
    teacher: "Hamraqulov Аʼzamjon Shermuxamedovich",
    type: "bakalavr",
    theme:
      "Oʼzbek adabiyotida Iskandar Zulqarnayin obrazi tadriji Sheralieva Mashhura Ikromjonovna",
    isBron: false,
  },
  {
    id: "18",
    facultyId: "1",
    kafedra: "O'zbek adabiyotshunosligi kafedrasi",
    teacher: "Shahobov Kamoldin Biloldinovich",
    type: "bakalavr",
    theme: "Nurmuhammad Аziz sheʼriyati gʼoyaviy-badiiy xususiyatlari",
    isBron: false,
  },
  {
    id: "19",
    facultyId: "1",
    kafedra: "O'zbek adabiyotshunosligi kafedrasi",
    teacher: "Shahobov Kamoldin Biloldinovich",
    type: "bakalavr",
    theme:
      "Yangi oʼzbek sheʼriyatida shakliy va mazmuniy evrilishlar (Najmiddin Ermatov sheʼriyati misolida)",
    isBron: false,
  },
  {
    id: "20",
    facultyId: "1",
    kafedra: "O'zbek adabiyotshunosligi kafedrasi",
    teacher: "Shahobov Kamoldin Biloldinovich",
    type: "bakalavr",
    theme:
      "Yangi oʼzbek sheʼriyatida shakliy va mazmuniy evrilishlar (Najmiddin Ermatov sheʼriyati misolida)",
    isBron: false,
  },
  {
    id: "21",
    facultyId: "1",
    kafedra: "O'zbek adabiyotshunosligi kafedrasi",
    teacher: "Shahobov Kamoldin Biloldinovich",
    type: "bakalavr",
    theme:
      "Yangi oʼzbek sheʼriyatida sahnaviylik (Erkin Bozorov ijodi misolida)",
    isBron: false,
  },
  {
    id: "22",
    facultyId: "1",
    kafedra: "O'zbek adabiyotshunosligi kafedrasi",
    teacher: "Shahobov Kamoldin Biloldinovich",
    type: "bakalavr",
    theme: "Halim Karim hikoyalarida ijtimoiy mavzuning badiiy talqini",
    isBron: false,
  },
  {
    id: "23",
    facultyId: "1",
    kafedra: "O'zbek adabiyotshunosligi kafedrasi",
    teacher: "Shahobov Kamoldin Biloldinovich",
    type: "bakalavr",
    theme:
      "Yangi oʼzbek sheʼriyatida shakliy va mazmuniy evrilishlar (Jontemir sheʼriyati misolida)",
    isBron: false,
  },
  {
    id: "24",
    facultyId: "1",
    kafedra: "O'zbek adabiyotshunosligi kafedrasi",
    teacher: "Shahobov Kamoldin Biloldinovich",
    type: "bakalavr",
    theme: "U.Hamdamovning “Ota” romanida xarakter va konflikt",
    isBron: false,
  },
  {
    id: "25",
    facultyId: "1",
    kafedra: "O'zbek adabiyotshunosligi kafedrasi",
    teacher: "Shahobov Kamoldin Biloldinovich",
    type: "bakalavr",
    theme:
      "Hozirgi oʼzbek nasrida shakliy va mazmuniy evrilishlar (U.Hamdam asarlari misolida)",
    isBron: false,
  },
  {
    id: "26",
    facultyId: "1",
    kafedra: "O'zbek adabiyotshunosligi kafedrasi",
    teacher: "Eshonova Zilola Qoʼchqarovna",
    type: "magistr",
    theme: 'Oʼzbek adabiyotida "Аrbaьin" anьanasi',
    isBron: false,
  },
  {
    id: "27",
    facultyId: "1",
    kafedra: "O'zbek adabiyotshunosligi kafedrasi",
    teacher: "Eshonova Zilola Qoʼchqarovna",
    type: "bakalavr",
    theme: 'Аlpomish" dostoni va marosim folьklori',
    isBron: false,
  },
  {
    id: "28",
    facultyId: "1",
    kafedra: "O'zbek adabiyotshunosligi kafedrasi",
    teacher: "Eshonova Zilola Qoʼchqarovna",
    type: "bakalavr",
    theme: "Usmon Аzim “Baxshiyona”lari poetikasi",
    isBron: false,
  },
  {
    id: "29",
    facultyId: "1",
    kafedra: "O'zbek adabiyotshunosligi kafedrasi",
    teacher: "Eshonova Zilola Qoʼchqarovna",
    type: "bakalavr",
    theme: "Uzbek sheьriyatida alla janri stilizatsiyasi",
    isBron: false,
  },
  {
    id: "30",
    facultyId: "1",
    kafedra: "O'zbek adabiyotshunosligi kafedrasi",
    teacher: "Eshonova Zilola Qoʼchqarovna",
    type: "bakalavr",
    theme: "Аdabiy topishmoklar poetikasi",
    isBron: false,
  },
  {
    id: "31",
    facultyId: "1",
    kafedra: "O'zbek adabiyotshunosligi kafedrasi",
    teacher: "Eshonova Zilola Qoʼchqarovna",
    type: "bakalavr",
    theme: 'Аlisher Navoiy "Xamsa"sida surushlarning funktsional xossalari',
    isBron: false,
  },
  {
    id: "32",
    facultyId: "1",
    kafedra: "O'zbek adabiyotshunosligi kafedrasi",
    teacher: "Eshonova Zilola Qoʼchqarovna",
    type: "bakalavr",
    theme: 'Navoiy ijodida "Meьrojnoma" lar',
    isBron: false,
  },
  {
    id: "33",
    facultyId: "1",
    kafedra: "O'zbek adabiyotshunosligi kafedrasi",
    teacher: "Eshonova Zilola Qoʼchqarovna",
    type: "bakalavr",
    theme: "Eshkobil Shukur ijodida folklor ananalari",
    isBron: false,
  },
  {
    id: "34",
    facultyId: "1",
    kafedra: "O'zbek adabiyotshunosligi kafedrasi",
    teacher: "Eshonova Zilola Qoʼchqarovna",
    type: "bakalavr",
    theme: "Rauf Subxon sheriyatida folklorizmlar tipologiyasi",
    isBron: false,
  },
  {
    id: "35",
    facultyId: "1",
    kafedra: "O'zbek adabiyotshunosligi kafedrasi",
    teacher: "Eshonova Zilola Qoʼchqarovna",
    type: "bakalavr",
    theme: "Normurod Narzullayev ijodida folklorizmlar",
    isBron: false,
  },
  {
    id: "36",
    facultyId: "1",
    kafedra: "O'zbek adabiyotshunosligi kafedrasi",
    teacher: "Eshonova Zilola Qoʼchqarovna",
    type: "bakalavr",
    theme: "Nazar Eshonnkul xikoyalari va folklor ",
    isBron: false,
  },
  {
    id: "37",
    facultyId: "1",
    kafedra: "O'zbek adabiyotshunosligi kafedrasi",
    teacher: "Eshonova Zilola Qoʼchqarovna",
    type: "bakalavr",
    theme: "Xalk kushiklari poetikasi",
    isBron: false,
  },
  {
    id: "38",
    facultyId: "1",
    kafedra: "O'zbek adabiyotshunosligi kafedrasi",
    teacher: "Azizov Nurmuxammad Ne’matillayevich",
    type: "magistr",
    theme: "Yoshlar she’riyati poetikasi (“Izlam” to‘plamlari misolida)",
    isBron: false,
  },
  {
    id: "39",
    facultyId: "1",
    kafedra: "O'zbek adabiyotshunosligi kafedrasi",
    teacher: "Azizov Nurmuxammad Ne’matillayevich",
    type: "bakalavr",
    theme: "Nazar Eshonqulning realistik asarlari badiiyati",
    isBron: false,
  },
  {
    id: "40",
    facultyId: "1",
    kafedra: "O'zbek adabiyotshunosligi kafedrasi",
    teacher: "Azizov Nurmuxammad Ne’matillayevich",
    type: "bakalavr",
    theme:
      "Nazar Eshonqulning norealistik asarlari badiiyati Ijodkor dunyoqarashining badiiy asardagi aksi masalasi (“Kecha va kunduz” va “Qutlug‘ qon” romanlari misolida)",
    isBron: false,
  },
  {
    id: "41",
    facultyId: "1",
    kafedra: "O'zbek adabiyotshunosligi kafedrasi",
    teacher: "Azizov Nurmuxammad Ne’matillayevich",
    type: "bakalavr",
    theme: "Istiqlol davri nasrida neomifologizm",
    isBron: false,
  },
  {
    id: "42",
    facultyId: "1",
    kafedra: "O'zbek adabiyotshunosligi kafedrasi",
    teacher: "Azizov Nurmuxammad Ne’matillayevich",
    type: "bakalavr",
    theme: "Eshqobil Shukur she’riyati poetikasi",
    isBron: false,
  },
  {
    id: "43",
    facultyId: "1",
    kafedra: "O'zbek adabiyotshunosligi kafedrasi",
    teacher: "Azizov Nurmuxammad Ne’matillayevich",
    type: "bakalavr",
    theme:
      "Hozirgi o‘zbek she’riyatida bolalik mavzusining yoritilishi (2000-2020 yillar misolida)",
    isBron: false,
  },
  {
    id: "44",
    facultyId: "1",
    kafedra: "O'zbek adabiyotshunosligi kafedrasi",
    teacher: "Azizov Nurmuxammad Ne’matillayevich",
    type: "bakalavr",
    theme: "Xurshid Do‘stmuhammad nasrida fantastik obrazlar talqini",
    isBron: false,
  },
  {
    id: "45",
    facultyId: "1",
    kafedra: "O'zbek adabiyotshunosligi kafedrasi",
    teacher: "Azizov Nurmuxammad Ne’matillayevich",
    type: "bakalavr",
    theme:
      "Ruhni shaytonga topshirish motivi talqinlari (“Faust” va “Ko‘zgu oldidagi odam” romani misolida)",
    isBron: false,
  },
  {
    id: "46",
    facultyId: "1",
    kafedra: "O'zbek adabiyotshunosligi kafedrasi",
    teacher: "Azizov Nurmuxammad Ne’matillayevich",
    type: "bakalavr",
    theme:
      "“Birinchi kitobim” loyihasida chiqqan she’riy kitoblar badiiyati (2020-2021-yil kitoblari misolida)",
    isBron: false,
  },
  {
    id: "47",
    facultyId: "1",
    kafedra: "O'zbek adabiyotshunosligi kafedrasi",
    teacher: "Azizov Nurmuxammad Ne’matillayevich",
    type: "bakalavr",
    theme:
      "“Birinchi kitobim”  loyihasida chiqqan she’riy kitoblar badiiyati (2022-2023-yil kitoblari misolida)",
    isBron: false,
  },
  {
    id: "48",
    facultyId: "1",
    kafedra: "O'zbek adabiyotshunosligi kafedrasi",
    teacher: "Qo‘chqarov Oybek Abdumansurovich",
    type: "magistr",
    theme: "Cho‘lpon she’riyati poetikasi.",
    isBron: false,
  },
  {
    id: "49",
    facultyId: "1",
    kafedra: "O'zbek adabiyotshunosligi kafedrasi",
    teacher: "Qo‘chqarov Oybek Abdumansurovich",
    type: "bakalavr",
    theme: "G‘afur G‘ulom nasrida yumor masalasi.",
    isBron: false,
  },
  {
    id: "50",
    facultyId: "1",
    kafedra: "O'zbek adabiyotshunosligi kafedrasi",
    teacher: "Qo‘chqarov Oybek Abdumansurovich",
    type: "bakalavr",
    theme: "Oybek she’riyatida poetik motivlar.",
    isBron: false,
  },
  {
    id: "51",
    facultyId: "1",
    kafedra: "O'zbek adabiyotshunosligi kafedrasi",
    teacher: "Qo‘chqarov Oybek Abdumansurovich",
    type: "bakalavr",
    theme: "Abdulla Qodiriyning portret yaratish san’ati.",
    isBron: false,
  },
  {
    id: "52",
    facultyId: "1",
    kafedra: "O'zbek adabiyotshunosligi kafedrasi",
    teacher: "Qo‘chqarov Oybek Abdumansurovich",
    type: "bakalavr",
    theme: "Abdulla Qodiriy asarlarida badiiy psixologizm",
    isBron: false,
  },
  {
    id: "53",
    facultyId: "1",
    kafedra: "O'zbek adabiyotshunosligi kafedrasi",
    teacher: "Qo‘chqarov Oybek Abdumansurovich",
    type: "bakalavr",
    theme: "Umar Xayyom she’riyatida falsafiy qarashlar.",
    isBron: false,
  },
  {
    id: "54",
    facultyId: "1",
    kafedra: "O'zbek adabiyotshunosligi kafedrasi",
    teacher: "Qo‘chqarov Oybek Abdumansurovich",
    type: "bakalavr",
    theme: "Faxriyor she’riyatining novatorlik xususiyatlari.",
    isBron: false,
  },
  {
    id: "55",
    facultyId: "1",
    kafedra: "O'zbek adabiyotshunosligi kafedrasi",
    teacher: "Qo‘chqarov Oybek Abdumansurovich",
    type: "bakalavr",
    theme: "Isajon Sulton asarlarida intertekstuallik.",
    isBron: false,
  },
  {
    id: "56",
    facultyId: "1",
    kafedra: "O'zbek adabiyotshunosligi kafedrasi",
    teacher: "Qo‘chqarov Oybek Abdumansurovich",
    type: "bakalavr",
    theme: "Najmiddin Ermatov she’riyatining o‘ziga xos xususiyatlari.",
    isBron: false,
  },
  {
    id: "57",
    facultyId: "1",
    kafedra: "O'zbek adabiyotshunosligi kafedrasi",
    teacher: "Qo‘chqarov Oybek Abdumansurovich",
    type: "bakalavr",
    theme: '"Husn va Dil" dostonida majoz masalasi.',
    isBron: false,
  },
  {
    id: "58",
    facultyId: "1",
    kafedra: "O'zbek adabiyotshunosligi kafedrasi",
    teacher: "Qo‘chqarov Oybek Abdumansurovich",
    type: "bakalavr",
    theme: "Elbek she’riyatida poetik motivlar",
    isBron: false,
  },
  {
    id: "59",
    facultyId: "1",
    kafedra: "O'zbek adabiyotshunosligi kafedrasi",
    teacher: "Islomova Sohiba Ismoiljonovna",
    type: "magistr",
    theme:
      "Uvaysiyning hamd, na’t, munojot g‘azallari matniy tadqiqi va poetikasi.",
    isBron: false,
  },
  {
    id: "60",
    facultyId: "1",
    kafedra: "O'zbek adabiyotshunosligi kafedrasi",
    teacher: "Islomova Sohiba Ismoiljonovna",
    type: "bakalavr",
    theme: "Uvaysiy chistonlarining matniy tadqiqi va poetikasi",
    isBron: false,
  },
  {
    id: "61",
    facultyId: "1",
    kafedra: "O'zbek adabiyotshunosligi kafedrasi",
    teacher: "Islomova Sohiba Ismoiljonovna",
    type: "bakalavr",
    theme: "Vosit Sa’dulla devonlari poetikasi.",
    isBron: false,
  },
  {
    id: "62",
    facultyId: "1",
    kafedra: "O'zbek adabiyotshunosligi kafedrasi",
    teacher: "Islomova Sohiba Ismoiljonovna",
    type: "bakalavr",
    theme:
      "Sulaymon bazzoz(Rasvo)ning hamd, na’t va munojot mavzusidagi g‘azallari poetikasi.",
    isBron: false,
  },
  {
    id: "63",
    facultyId: "1",
    kafedra: "O'zbek adabiyotshunosligi kafedrasi",
    teacher: "Islomova Sohiba Ismoiljonovna",
    type: "bakalavr",
    theme:
      "Cho‘lponning aruz vaznida yaratilgan she’rlarida badiiy san’atlardan foydalanish mahorati.",
    isBron: false,
  },
  {
    id: "64",
    facultyId: "1",
    kafedra: "O'zbek adabiyotshunosligi kafedrasi",
    teacher: "Islomova Sohiba Ismoiljonovna",
    type: "bakalavr",
    theme:
      "Uvaysiyning g‘azallarida she’riy san’atlardan foydalanish mahorati.",
    isBron: false,
  },
  {
    id: "65",
    facultyId: "1",
    kafedra: "O'zbek adabiyotshunosligi kafedrasi",
    teacher: "Islomova Sohiba Ismoiljonovna",
    type: "bakalavr",
    theme: "Uvaysiy lirikasida talmeh she’riy san’atining tutgan o‘rni",
    isBron: false,
  },
  {
    id: "66",
    facultyId: "1",
    kafedra: "O'zbek adabiyotshunosligi kafedrasi",
    teacher: "Islomova Sohiba Ismoiljonovna",
    type: "bakalavr",
    theme: "Andijon adabiy muhiti vakillari ijodida mushoara janri",
    isBron: false,
  },
  {
    id: "67",
    facultyId: "1",
    kafedra: "O'zbek adabiyotshunosligi kafedrasi",
    teacher: "Islomova Sohiba Ismoiljonovna",
    type: "bakalavr",
    theme:
      "“O‘zbek yosh shoirlari” to‘plamidagi Cho‘lpon she’rlarining matniy tadqiqi va poetikasi.",
    isBron: false,
  },
  {
    id: "68",
    facultyId: "1",
    kafedra: "O'zbek adabiyotshunosligi kafedrasi",
    teacher: "Islomova Sohiba Ismoiljonovna",
    type: "bakalavr",
    theme:
      "Cho‘lponning joriy nashrlardagi she’rlari matniy tadqiqi va poetikasi.",
    isBron: false,
  },
  {
    id: "69",
    facultyId: "1",
    kafedra: "O'zbek adabiyotshunosligi kafedrasi",
    teacher: "Islomova Sohiba Ismoiljonovna",
    type: "bakalavr",
    theme:
      "Cho‘lpon she’riyatida yondosh matn(ramka unsurlari)ning tutgan o‘rni.",
    isBron: false,
  },
  {
    id: "70",
    facultyId: "1",
    kafedra: "O'zbek adabiyotshunosligi kafedrasi",
    teacher: "Mo‘minov Begali Yunusovich",
    type: "bakalavr",
    theme:
      "Alisher Navoiy siymosining badiiy talqini ( Oybek va Isajon sulton romanlari misolida).",
    isBron: false,
  },
];
